name: time-manager
recipe: lamp
config:
  php: '7.4'
  webroot: '/'
  database: mysql
services:
  database:
    type: mysql
    creds:
      password: root
      database: elioooftime
  phpmyadmin:
    portforward: true
    type: phpmyadmin
    hosts:
      - database
proxy:
  appserver:
    - time-manager.lndo.site

# lando db import